---
# tasks file for user_clone

#------------------------#
#  user_clone
#
# - Obtengo INFO del usuario del equipo HOST desde donde se disparo el playbook
# - Creo en el Host remoto, el mismo Usuario, con la misma clave
# - Cruzo la clave ssh del usuario local, contra el Usuario remoto
#------------------------#

- debug:
    msg: " ---- Creacion de usuarios ----"

- name: "Get USERNAME local "
  set_fact:
    USERNAME: "{{ lookup('env','USER') }}"
    
- name: get hash password {{ USERNAME }}
  become: yes
  local_action: shell grep  {{ USERNAME }} /etc/shadow |awk -F ':' '{print $2}'
  register: PASSWORD_SHA512

- name: "create user: {{ USERNAME }} whith equal Password local host"
  become: yes
  user:
    name: "{{ USERNAME }}"
    password: "{{ PASSWORD_SHA512.stdout }}"
    groups: "{{ GROUP_ADMIN }}"


- name: Add Clave Publica en authorized 
  become: yes
  authorized_key:
    user: "{{ USERNAME }}"
    key: "{{ lookup('file', '{{ item }}') }}"
    state: present
  with_fileglob: "{{ lookup('env','HOME') + '/.ssh/*.pub' }}"
