---

#------------------------#
#  Seteo de Variables de acuerdo al SO
#------------------------#

#-------- Debian y derivados ----------------#
- name: "Set GROUP_ADMIN - Debian_family"
  set_fact:
    GROUP_ADMIN: "{{ DEBIAN_GROUP_ADMIN }}"
  when: ansible_facts['os_family'] == "Debian"


#-------- RedHat y derivados ----------------#
- name: "Set GROUP_ADMIN - RedHat_family"
  set_fact:
    GROUP_ADMIN: "{{ REDHAT_GROUP_ADMIN }}"
  when: ansible_facts['os_family'] == "RedHat"


#----------- Generales ---------------------#

- name: "Conocer si tiene ip dinamica"
  become: yes
  shell: "ip addr show |grep {{ ansible_default_ipv4.address }} | grep -i dynamic -c "
  register: is_ip_dinamic


