---

- debug:
    msg: " ---- Creacion de usuarios ----"




- name: Set USERNAME
  set_fact:
    USERNAME: "{{ lookup('env','USER') }}"
    
- name: get hash password {{ USERNAME }}
  become: yes
  local_action: shell grep  {{ USERNAME }} /etc/shadow |awk -F ':' '{print $2}'
  register: PASSWORD_SHA512




- name: "create user: {{ USERNAME }} whith equal Password local host - RedHat y derivados"
  become: yes
  user:
    name: "{{ USERNAME }}"
    password: "{{ PASSWORD_SHA512.stdout }}"
    groups: wheel
    when: (ansible_facts['os_family'] == "RedHat" ) 

- name: Add Clave Publica en authorized 
  become: yes
  authorized_key:
    user: "{{ USERNAME }}"
    key: "{{ lookup('file', '{{ item }}') }}"
    state: present
  with_fileglob: "{{ lookup('env','HOME') + '/.ssh/*.pub' }}"
