---

- debug:
    msg: "---- Realizando Configuraciones genericas  ----"

- name: "add NOPASSWD in sudores for group sudo"
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'


- name: Put SELinux in permissive mode, logging actions that would be blocked.
  become: yes
  ansible.posix.selinux:
    policy: targeted
    state: permissive


- name: "Upload archivos configuracion"
  become: yes
  copy:
    src: "{{ item }}"
    dest: /etc/profile.d/
    owner: root
    group: root
    #mode: 0755
  with_items:
    - 00-aliases.sh

- name: "Quitar nano como editor por defecto" 
  become: yes
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - nano-default-editor

- name: "Agregar vim como editor por defecto" 
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - vim-default-editor
  
- name: Set HOME
  set_fact:
    HOME: "{{ lookup('env','HOME') }}"

- name: "copio autostart de dnfdragora-updater para luego deshabilitarlo"
  copy:
    src: "{{ item }}"
    dest: "{{ HOME}}/.config/autostart/"
  with_items:
    - /etc/xdg/autostart/org.mageia.dnfdragora-updater.desktop

- name: "deshabilita dnfdragora-updater"
  #become: yes
  lineinfile:
    dest: "{{ HOME }}/.config/autostart/org.mageia.dnfdragora-updater.desktop"
    line: 'Hidden=true'
    state: present

- name: "killall dnfdragora-updater"
  become: yes 
  shell: killall dnfdragora-updater

  