---

- debug:
    msg: "---- Instalacion de paquetes  ----"

- name: "Include Instalacion paquetes genericos"
  include_tasks: fedora/003_instalacion_genericos_fedora.yml
  when: ansible_facts['distribution'] == "Fedora"

- name: "Include Instalacion paquetes genericos"
  include_tasks: ubuntu/003_instalacion_genericos_ubuntu.yml
  when: ansible_facts['distribution'] == "Ubuntu"

- name: "Instalar paquetes basicos" 
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ca-certificates
    - curl
    - vim
    - gnupg2
    - policycoreutils
    - "{{ chrome_app_name }}"   #Los repos oficiales se agregan dependiendo del SO
    - terminator
    - wmctrl
    - htop
    


- name: "Instalar paquetes de redes" 
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - tcpdump
    - fail2ban

- name: "Instalar paquetes para conectarse escritorios remotos" 
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - virt-viewer
    - remmina
    - anydesk

- name: "anydesk -silent --restart-service"
  become: yes
  shell: "anydesk --silent --restart-service"

- name: "anydesk get_id"
  shell: "anydesk --get-id"
  register: ID_ANYDESK

- debug:
    msg: "ID Anydesk: {{ ID_ANYDESK.stdout }}"

