---

- debug:
    msg: "---- Instalacion de paquetes  ----"

- name: "Instalar paquetes basicos" 
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ca-certificates
    - curl
    - vim
    - gnupg2
    - fedora-workstation-repositories
    - dnf-plugins-core
    
- name: Instalo google-chrome desde el repo de google
  become: yes
  dnf:
    name: google-chrome-stable
    enablerepo: google-chrome
    state: present


- name: "Instalar paquetes de redes" 
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - tcpdump
    - fail2ban

    