---

- debug:
    msg: " ---- installacion / configuracion Compiz ----"

- name: "Include 014_entorno_grafico_compiz_fedora"
  include: fedora/014_entorno_grafico_compiz_fedora.yml
  when: ansible_facts['distribution'] == "Fedora"

- name: "Include 014_entorno_grafico_compiz_ubuntu"
  include: ubuntu/014_entorno_grafico_compiz_ubuntu.yml
  when: ansible_facts['distribution'] == "Ubuntu"

#Deshabilita compiz
#gsettings reset org.mate.session.required-components windowmanager


- name: "Copy script import config compiz"
  copy:
    src: "GUI/compiz_config.py"
    dest: "{{ ansible_env.HOME }}/scipts/"
    mode: '0755'
   


- pause:
    prompt: "Falta realizar importacion de la configuracion de compiz"

