---

# - name: "Include Instalacion paquetes desarrollo"
#   include: ubuntu/011_instalacion_desarrollo_ubuntu.yml
#   when: ansible_facts['distribution'] == "Ubuntu"

#https://ubunlog.com/como-instalar-compiz-en-ubuntu-mate/
#---------- para ubuntu... los paquetes en fedora son distintos
- name: "Instalar paquetes compiz" 
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - compiz
    - compiz-plugins
    - compizconfig-settings-manager
  when: ansible_facts['distribution'] == "Ubuntu"

- name: "Setea compiz como manejador de ventanas por defecto"
#  become: yes 
  shell: "gsettings set org.mate.session.required-components windowmanager compiz"
  when: ansible_facts['distribution'] == "Ubuntu"


- pause:
    prompt: "Para ver el cambio, debe relogiarse a la session grafica en el host remoto"

#Deshabilita compiz
#gsettings reset org.mate.session.required-components windowmanager
