---

- debug:
    msg: "---- Realizando Configuraciones genericas  ----"

- name: "add NOPASSWD in sudores for group sudo"
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

#no me esta tomando bien los alias...
- name: "Upload archivos configuracion"
  become: yes
  copy:
    src: "{{ item }}"
    dest: /etc/profile.d/
    owner: root
    group: root
    #mode: 0755
  with_items:
    - 00-aliases.sh
  tags:
      - conf_genericos

- name: "Quitar nano como editor por defecto" 
  become: yes
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - nano-default-editor

- name: "Agregar vim como editor por defecto" 
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - vim-default-editor
    

# - name: Correct editor default selected
#   become: yes
#   alternatives:
#     name: EDITOR
#     path: /usr/bin/vim
#     link: /etc/alternatives/editor

# - name: Set vim as the default editor
#   become: yes
#   shell: "/usr/sbin/update-alternatives --set editor /usr/bin/vim || /usr/bin/update-alternatives --set editor /usr/bin/vim"
# #  when: editor.stat.lnk_source != '/usr/bin/vim'




