---

- debug:
    msg: "---- INICIA ----"

- name: "Include creacion de usuarios"
  include: 000_hosts.yml
  tags:
    - host_config

- name: "Include creacion de usuarios"
  include: 001_crear_usuario.yml
  tags:
    - user_config
    - never

- name: "Realiza configuraciones genericas"
  include: 002_config_genericas.yml
  tags:
    - config_genericos

- name: "Include Instalacion paquetes genericos"
  include: 010_instalacion_genericos.yml
  tags:
    - install_genericos

- name: "Include Instalacion paquetes desarrollo"
  include: 011_instalacion_desarrollo.yml
  tags:
    - install_desarrollo

- name: "Include Instalacion paquetes desarrollo"
  include: 012_add_docker_fedora.yml
  when: ansible_facts['distribution'] == "Fedora"
  tags:
    - add_docker

- name: "Install VirtualBox"
  include: 013_add_VirtualBox_fedora.yml
  when: ansible_facts['distribution'] == "Fedora"
  tags:
    - add_VirtualBox

#--- usado para realizar pruebas ---#
- name: "Pruebas - No incluir"
  include: pruebas.yml
  tags:
    - never
    - pruebas


