---

#--- usado para realizar pruebas ---#
- name: "Pruebas - No incluir"
  include: _prueba/pruebas.yml
  tags:
    - never
    - pruebas


- debug:
    msg: "---- INICIA ----"

- name: "Seteo Variables segun OS_Family"
  include: 000_set_vars.yml
  tags:
    - always
    - set_vars

- name: "Include creacion de usuarios"
  include: 001_hosts.yml
  tags:
    - host_config

- name: "Include creacion de usuarios"
  include: 002_crear_usuario.yml
  tags:
    - user_config
    - never

#-------- install paquetes genericos ------#

#Incluye llamadas a los yml segun SO
- name: "Include Instalacion paquetes genericos"
  include: 003_instalacion_genericos.yml
  tags:
    - install_genericos


#---------- Config Genericas -------------#
- name: "Realiza configuraciones genericas"
  include: 004_config_genericas.yml
  tags:
    - config_genericos


- name: "Fix-Bug_kernel_207759_Touchpad"
  include: 005_Fix-KernelBug_207759_touchpad.yml
  tags:
    - Fix-KernelBug_207759


#----------- Herramientas de desarrollo ----#
- name: "Include Instalacion paquetes desarrollo"
  include: 011_instalacion_desarrollo.yml
  tags:
    - install_desarrollo

- name: "Instalacion / Configuracion compiz"
  include: 014_entorno_grafico_compiz.yml
  tags:
    - compiz

#----- Herramientas de virtualizacion microservicios y vm -----#
- name: "Include Docker"
  include: 012_add_docker.yml
  tags:
    - add_docker

- name: "Install VirtualBox"
  include: 013_add_VirtualBox.yml
  tags:
    - add_VirtualBox

- name: "Install plataformas de games"
  include: 020_Games.yml
  tags:
    - add_Games

