# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "gusztavvargadr/ubuntu-desktop-2404-lts"

  #config.vm.synced_folder '.', '/home/vagrant/foo'
  config.vm.hostname = "VMPruebas"
  config.vm.define :VMPruebas do |t|
  end

 
  config.vm.network "private_network", :name => 'vboxnet0', ip: "192.168.56.100"


  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
      # vb.memory = "1024"
      vb.memory = "2048"
      vb.name = "VMPruebas"
      vb.cpus = 2
      vb.linked_clone = true
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    sudo systemctl restart sshd
  SHELL

end
