---




- name: "add repo oficial sublime"
  become: yes 
  shell: dnf config-manager --add-repo https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo

- name: "Add repositories Visual Studio Code"
  become: yes
  yum_repository:
    file: "{{ visualStudioCode_repo_filename }}.repo"
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: 1
    gpgcheck: yes
    gpgkey: "{{ VSCode_gpg_key }}"
