---

#----------------------------------------#
# Install y config VirtualBox en fedora
#----------------------------------------#


- name: "Instalar dependencias " 
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "@development-tools"
    - kernel-headers
    - kernel-devel
    - dkms
    - elfutils-libelf-devel
    - qt5-qtx11extras

- name: "add repo oficial VirtualBox"
  become: yes 
  shell: dnf config-manager --add-repo http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo

- name: "Set VirtualBox APP - Fedora"
  set_fact:
    VirtualBox_APP: "{{ virtualbox_app_rpm }}"
    VIRTUALBOX_GUEST_ADDITIONS: "{{ virtualbox_guest_additions_rpm }}"
  #when: ansible_facts['distribution'] == "Fedora"

