---

- name: "Set EpicGame vars"
  set_fact:
    EpicGame_URL_APP: "{{ EpicGame_URL}}{{ EpicGame_app_rpm }}"
    EpicGame_APP: "{{ EpicGame_app_rpm | basename }}"

- name: "add repo rpmfusion" 
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

