---


#Muestro todas las variables
# - debug:
#     msg: 
#       - "{{ ansible_facts }}"
#       # - "{{ ansible_default_ipv4.address }} "




- debug:
    msg: 
      - "{{ ansible_facts.lsb.codename }}"



#modificar entrada del menu de efi
#https://www.linuxbabe.com/command-line/how-to-use-linux-efibootmgr-examples
#https://linuxmint-installation-guide.readthedocs.io/es/latest/efi.html



