---



  #update-alternatives --set editor /usr/bin/vim.basic
# - name: Alternatives link created editor
#   community.general.alternatives:
#     name: editor
#     link: /usr/bin/vim.basic
#     path: /usr/bin/vim.basic.ansible

#fallo en ubuntu (no puede tener el mismo nomrbe en el link que en el path)
# - name: Alternatives link created editor
#   become: yes
#   community.general.alternatives:
#     name: editor
#     link: /usr/bin/vim
#     path: /usr/bin/vim

- name: Make editor alternative with low priority
  become: yes
  community.general.alternatives:
    name: editor
    path: /usr/bin/vim.basic
    priority: -10

- name: set localhost in /etc/hosts
  become: yes
  lineinfile:
    state: present
    dest: /etc/default/keyboard
    line: 'XKBOPTIONS="terminate:ctrl_alt_bksp"'


