---

#----------------------------------------#
# Install y config VirtualBox en ubuntu
#----------------------------------------#

- name: Debian/Ubuntu Family | Add gpg signing key for virtualbox
  become: yes
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "{{ virtualbox_gpg_key_01 }}"
    - "{{ virtualbox_gpg_key_02 }}"

- name: "Debian/Ubuntu Family | Adding repository VirtualBox"
  become: yes
  apt_repository:
    repo: "{{ VirtualBox_repo_debian }}"
    filename: "{{ VirtualBox_repo_filename }}"
    state: present
    update_cache: yes


- name: "Set VirtualBox APP - Ubuntu"
  set_fact:
    VirtualBox_APP: "{{ virtualbox_app_deb }}"
    VIRTUALBOX_GUEST_ADDITIONS: "{{ virtualbox_guest_additions_deb }}"

# - name: "Set VirtualBox APP - Ubuntu"
#   set_fact:
#  #   VirtualBox_APP: "{{ virtualbox_app_deb }}"
#     VIRTUALBOX_GUEST_ADDITIONS: "{{ virtualbox_guest_additions_deb }}"

