---

#https://ubunlog.com/como-instalar-compiz-en-ubuntu-mate/

#---------- para ubuntu... los paquetes en fedora son distintos
- name: "Instalar paquetes compiz" 
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - compiz
    - compiz-plugins
    - compizconfig-settings-manager
 
- name: "Setea compiz como manejador de ventanas por defecto"
  shell: "gsettings set org.mate.session.required-components windowmanager compiz"
 

- name: "Instalar paquetes para importar configuracion de compiz" 
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-compizconfig # para ubuntu
#    - compizconfig-python #(validado en fedora)

