---

#seteo de variables

chrome_app_name: google-chrome-stable
steam_app_deb: steam-launcher
steam_app_rpm: steam
virtualbox_app_rpm: VirtualBox-7.1
virtualbox_guest_additions_rpm: virtualbox-guest-additions

#------- Comunes entra las distros --------#
chrome_repo_filename: google-chrome
sublime_repo_filename: sublime-text
visualStudioCode_repo_filename: vscode
anydesk_repo_filename: anydesk-stable
docker_repo_filename: docker
steam_repo_filename: steam

#GPG_key
chrome_gpg_key: "https://dl.google.com/linux/linux_signing_key.pub"
sublime_gpg_key: "https://download.sublimetext.com/sublimehq-pub.gpg"
VSCode_gpg_key: "https://packages.microsoft.com/keys/microsoft.asc"

anydesk_gpg_key_DEB: "https://keys.anydesk.com/repos/DEB-GPG-KEY"
anydesk_gpg_key_RPM: "https://keys.anydesk.com/repos/RPM-GPG-KEY"

docker_gpg_key_DEB: "https://download.docker.com/linux/ubuntu/gpg"
steam_gpg_IDkey_DEB: "B05498B7"



#------- Ubuntu --------#
# Nombres de aplicacion virtualbox en debian y derivados
virtualbox_app_deb:
virtualbox_guest_additions_deb:

#Variables para debian y derivados
DEBIAN_GROUP_ADMIN: "sudo"
DEBIAN_GROUPS_DEFAULS: "cdrom,dip,plugdev,lpadmin,lxd,sambashare"

#Repos 
chrome_repo_debian:     "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
sublime_repo_debian:    "deb https://download.sublimetext.com/ apt/stable/"
vscode_repo_debian:     "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
anydesk_repo_debian:    "deb http://deb.anydesk.com/ all main"
steam_repo_debian:      "deb http://repo.steampowered.com/steam/ precise steam"

docker_repo_debian:     "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"


#------- Fedora --------#
#Variables para RedHat y derivados
REDHAT_GROUP_ADMIN: "wheel"
REDHAT_GROUPS_DEFAULS: ""
